// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYvo15Sg3PBPpJMUzRpTlclEo-mriN0zI',
    appId: '1:626911680712:web:1a95fdd7277c4a17136dfd',
    messagingSenderId: '626911680712',
    projectId: 'marketplace-46f33',
    authDomain: 'marketplace-46f33.firebaseapp.com',
    storageBucket: 'marketplace-46f33.appspot.com',
    measurementId: 'G-G0LLZGJRCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf3IzyasAyv8-Lc28PA7zMJqSK8q185-4',
    appId: '1:626911680712:android:a0311070e463eb69136dfd',
    messagingSenderId: '626911680712',
    projectId: 'marketplace-46f33',
    storageBucket: 'marketplace-46f33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_qfcBXsMOWvjxJHqJwxzkVl6csdqzujA',
    appId: '1:626911680712:ios:759aade7d4db03bc136dfd',
    messagingSenderId: '626911680712',
    projectId: 'marketplace-46f33',
    storageBucket: 'marketplace-46f33.appspot.com',
    iosBundleId: 'com.example.marketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_qfcBXsMOWvjxJHqJwxzkVl6csdqzujA',
    appId: '1:626911680712:ios:05334f0bee7feea4136dfd',
    messagingSenderId: '626911680712',
    projectId: 'marketplace-46f33',
    storageBucket: 'marketplace-46f33.appspot.com',
    iosBundleId: 'com.example.marketplace.RunnerTests',
  );
}
